<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [

            // ================= REGISTRATION =================
            [
                'name' => 'Biaya Pendaftaran Sekolah',
                'description' => 'Biaya administrasi pendaftaran siswa baru',
                'name_id' => 'Biaya Pendaftaran Sekolah',
                'description_id' => 'Biaya administrasi pendaftaran siswa baru',
                'name_en' => 'School Registration Fee',
                'description_en' => 'New student enrollment administration fee',
                'category' => 'registration',
                'price' => 150000,
            ],
            [
                'name' => 'SPP SD',
                'description' => 'Biaya SPP bulanan tingkat SD',
                'name_id' => 'SPP SD',
                'description_id' => 'Biaya SPP bulanan tingkat SD',
                'name_en' => 'Elementary Tuition Fee (SPP SD)',
                'description_en' => 'Monthly tuition for Elementary level',
                'category' => 'registration',
                'price' => 250000,
            ],
            [
                'name' => 'SPP SMP',
                'description' => 'Biaya SPP bulanan tingkat SMP',
                'name_id' => 'SPP SMP',
                'description_id' => 'Biaya SPP bulanan tingkat SMP',
                'name_en' => 'Junior High Tuition Fee (SPP SMP)',
                'description_en' => 'Monthly tuition for Junior High level',
                'category' => 'registration',
                'price' => 300000,
            ],

            // ================= EXAMS =================
            [
                'name' => 'Biaya UTS SD',
                'description' => 'Biaya ujian tengah semester tingkat SD',
                'name_id' => 'Biaya UTS SD',
                'description_id' => 'Biaya ujian tengah semester tingkat SD',
                'name_en' => 'Elementary Mid-Semester Exam Fee',
                'description_en' => 'Mid-term exam fee for elementary',
                'category' => 'exams',
                'price' => 125000,
            ],
            [
                'name' => 'Biaya UTS SMP',
                'description' => 'Biaya ujian tengah semester tingkat SMP',
                'name_id' => 'Biaya UTS SMP',
                'description_id' => 'Biaya ujian tengah semester tingkat SMP',
                'name_en' => 'Junior High Mid-Semester Exam Fee',
                'description_en' => 'Mid-term exam fee for junior high',
                'category' => 'exams',
                'price' => 150000,
            ],
            [
                'name' => 'Biaya UAS SD',
                'description' => 'Biaya ujian akhir semester tingkat SD',
                'name_id' => 'Biaya UAS SD',
                'description_id' => 'Biaya ujian akhir semester tingkat SD',
                'name_en' => 'Elementary Final Semester Exam Fee',
                'description_en' => 'End-of-semester exam for elementary',
                'category' => 'exams',
                'price' => 175000,
            ],
            [
                'name' => 'Biaya UAS SMP',
                'description' => 'Biaya ujian akhir semester tingkat SMP',
                'name_id' => 'Biaya UAS SMP',
                'description_id' => 'Biaya ujian akhir semester tingkat SMP',
                'name_en' => 'Junior High Final Semester Exam Fee',
                'description_en' => 'End-of-semester exam for junior high',
                'category' => 'exams',
                'price' => 200000,
            ],
            [
                'name' => 'Biaya Ujian Kelulusan SD',
                'description' => 'Biaya ujian kelulusan tingkat SD',
                'name_id' => 'Biaya Ujian Kelulusan SD',
                'description_id' => 'Biaya ujian kelulusan tingkat SD',
                'name_en' => 'Elementary Graduation Exam Fee',
                'description_en' => 'Graduation exam fee for elementary',
                'category' => 'exams',
                'price' => 180000,
            ],
            [
                'name' => 'Biaya Ujian Kelulusan SMP',
                'description' => 'Biaya ujian kelulusan tingkat SMP',
                'name_id' => 'Biaya Ujian Kelulusan SMP',
                'description_id' => 'Biaya ujian kelulusan tingkat SMP',
                'name_en' => 'Junior High Graduation Exam Fee',
                'description_en' => 'Graduation exam fee for junior high',
                'category' => 'exams',
                'price' => 200000,
            ],

            // ================= BOOKS =================
            [
                'name' => 'Buku Pendidikan Agama Kristen',
                'description' => 'Buku pelajaran Pendidikan Agama Kristen',
                'name_id' => 'Buku Pendidikan Agama Kristen',
                'description_id' => 'Buku pelajaran Pendidikan Agama Kristen',
                'name_en' => 'Christian Religious Education Book',
                'description_en' => 'Textbook for Christian Religious Education',
                'category' => 'book',
                'price' => 55000,
            ],
            [
                'name' => 'Buku Matematika',
                'description' => 'Buku pelajaran Matematika',
                'name_id' => 'Buku Matematika',
                'description_id' => 'Buku pelajaran Matematika',
                'name_en' => 'Mathematics Textbook',
                'description_en' => 'Mathematics learning textbook',
                'category' => 'book',
                'price' => 60000,
            ],
            [
                'name' => 'Buku Bahasa Indonesia',
                'description' => 'Buku pelajaran Bahasa Indonesia',
                'name_id' => 'Buku Bahasa Indonesia',
                'description_id' => 'Buku pelajaran Bahasa Indonesia',
                'name_en' => 'Bahasa Indonesia Textbook',
                'description_en' => 'Bahasa Indonesia learning textbook',
                'category' => 'book',
                'price' => 55000,
            ],
            [
                'name' => 'Buku PPKN',
                'description' => 'Buku pelajaran Pendidikan Pancasila dan Kewarganegaraan',
                'name_id' => 'Buku PPKN',
                'description_id' => 'Buku pelajaran Pendidikan Pancasila dan Kewarganegaraan',
                'name_en' => 'Civics (PPKN) Textbook',
                'description_en' => 'Civics subject textbook',
                'category' => 'book',
                'price' => 50000,
            ],
            [
                'name' => 'Buku Seni Budaya',
                'description' => 'Buku pelajaran Seni Budaya dan Prakarya',
                'name_id' => 'Buku Seni Budaya',
                'description_id' => 'Buku pelajaran Seni Budaya dan Prakarya',
                'name_en' => 'Arts & Culture (SBDP) Textbook',
                'description_en' => 'Arts and culture textbook',
                'category' => 'book',
                'price' => 50000,
            ],
            [
                'name' => 'Buku Penjas',
                'description' => 'Buku pelajaran Pendidikan Jasmani',
                'name_id' => 'Buku Penjas',
                'description_id' => 'Buku pelajaran Pendidikan Jasmani',
                'name_en' => 'Physical Education (PE) Textbook',
                'description_en' => 'PE subject textbook',
                'category' => 'book',
                'price' => 52000,
            ],
            [
                'name' => 'Buku Bahasa Inggris',
                'description' => 'Buku pelajaran Bahasa Inggris',
                'name_id' => 'Buku Bahasa Inggris',
                'description_id' => 'Buku pelajaran Bahasa Inggris',
                'name_en' => 'English Textbook',
                'description_en' => 'English learning textbook',
                'category' => 'book',
                'price' => 60000,
            ],
            [
                'name' => 'Buku IPA',
                'description' => 'Buku pelajaran Ilmu Pengetahuan Alam',
                'name_id' => 'Buku IPA',
                'description_id' => 'Buku pelajaran Ilmu Pengetahuan Alam',
                'name_en' => 'Science (IPA) Textbook',
                'description_en' => 'Science subject textbook',
                'category' => 'book',
                'price' => 65000,
            ],
            [
                'name' => 'Buku IPS',
                'description' => 'Buku pelajaran Ilmu Pengetahuan Sosial',
                'name_id' => 'Buku IPS',
                'description_id' => 'Buku pelajaran Ilmu Pengetahuan Sosial',
                'name_en' => 'Social Studies (IPS) Textbook',
                'description_en' => 'Social studies textbook',
                'category' => 'book',
                'price' => 62000,
            ],
            [
                'name' => 'Buku Prakarya',
                'description' => 'Buku pelajaran Prakarya dan Keterampilan',
                'name_id' => 'Buku Prakarya',
                'description_id' => 'Buku pelajaran Prakarya dan Keterampilan',
                'name_en' => 'Handcraft & Skills Book',
                'description_en' => 'Handcraft and skills textbook',
                'category' => 'book',
                'price' => 48000,
            ],

            // ================= ITEMS =================
            [
                'name' => 'Seragam Sekolah',
                'description' => 'Seragam sekolah lengkap',
                'name_id' => 'Seragam Sekolah',
                'description_id' => 'Seragam sekolah lengkap',
                'name_en' => 'School Uniform',
                'description_en' => 'Complete school uniform',
                'category' => 'items',
                'price' => 180000,
            ],
            [
                'name' => 'Kartu Pelajar',
                'description' => 'Kartu identitas resmi siswa',
                'name_id' => 'Kartu Pelajar',
                'description_id' => 'Kartu identitas resmi siswa',
                'name_en' => 'Student ID Card',
                'description_en' => 'Official student identification card',
                'category' => 'items',
                'price' => 35000,
            ],
            [
                'name' => 'Tali ID Card',
                'description' => 'Tali gantungan kartu pelajar',
                'name_id' => 'Tali ID Card',
                'description_id' => 'Tali gantungan kartu pelajar',
                'name_en' => 'Lanyard',
                'description_en' => 'Lanyard for ID card',
                'category' => 'items',
                'price' => 15000,
            ],
            [
                'name' => 'Paket Seragam Lengkap',
                'description' => 'Paket seragam, kartu pelajar, dan lanyard',
                'name_id' => 'Paket Seragam Lengkap',
                'description_id' => 'Paket seragam, kartu pelajar, dan lanyard',
                'name_en' => 'Uniform + ID Card + Lanyard Set',
                'description_en' => 'Full set: uniform, ID card, and lanyard',
                'category' => 'items',
                'price' => 220000,
            ],
            [
                'name' => 'Toga Wisuda SD',
                'description' => 'Toga wisuda untuk siswa SD',
                'name_id' => 'Toga Wisuda SD',
                'description_id' => 'Toga wisuda untuk siswa SD',
                'name_en' => 'Elementary Graduation Gown',
                'description_en' => 'Graduation gown for elementary students',
                'category' => 'items',
                'price' => 200000,
            ],
            [
                'name' => 'Toga Wisuda SMP',
                'description' => 'Toga wisuda untuk siswa SMP',
                'name_id' => 'Toga Wisuda SMP',
                'description_id' => 'Toga wisuda untuk siswa SMP',
                'name_en' => 'Junior High Graduation Gown',
                'description_en' => 'Graduation gown for junior high students',
                'category' => 'items',
                'price' => 220000,
            ],

            // ================= PROGRAMS =================
            [
                'name' => 'Biaya Kegiatan Ekstrakurikuler',
                'description' => 'Biaya kegiatan ekstrakurikuler siswa',
                'name_id' => 'Biaya Kegiatan Ekstrakurikuler',
                'description_id' => 'Biaya kegiatan ekstrakurikuler siswa',
                'name_en' => 'Extracurricular Activity Fee',
                'description_en' => 'Fee for extracurricular programs',
                'category' => 'programs',
                'price' => 160000,
            ],
            [
                'name' => 'Biaya Kegiatan Praktik',
                'description' => 'Biaya kegiatan praktik siswa',
                'name_id' => 'Biaya Kegiatan Praktik',
                'description_id' => 'Biaya kegiatan praktik siswa',
                'name_en' => 'Practical Activity Fee',
                'description_en' => 'Hands-on practical activity fee',
                'category' => 'programs',
                'price' => 85000,
            ],
            [
                'name' => 'Biaya Wisuda SD',
                'description' => 'Biaya acara wisuda tingkat SD',
                'name_id' => 'Biaya Wisuda SD',
                'description_id' => 'Biaya acara wisuda tingkat SD',
                'name_en' => 'Elementary Graduation Ceremony Fee',
                'description_en' => 'Graduation ceremony cost for elementary',
                'category' => 'programs',
                'price' => 300000,
            ],
            [
                'name' => 'Biaya Wisuda SMP',
                'description' => 'Biaya acara wisuda tingkat SMP',
                'name_id' => 'Biaya Wisuda SMP',
                'description_id' => 'Biaya acara wisuda tingkat SMP',
                'name_en' => 'Junior High Graduation Ceremony Fee',
                'description_en' => 'Graduation ceremony cost for junior high',
                'category' => 'programs',
                'price' => 350000,
            ],
            [
                'name' => 'Biaya Kegiatan Sekolah Offline',
                'description' => 'Biaya kegiatan sekolah luar kelas',
                'name_id' => 'Biaya Kegiatan Sekolah Offline',
                'description_id' => 'Biaya kegiatan sekolah luar kelas',
                'name_en' => 'Offline School Activity Fee',
                'description_en' => 'Fee for offline school events and outings',
                'category' => 'programs',
                'price' => 120000,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
